import { Fragment, useEffect, useRef, useState, type ChangeEvent, type FormEvent } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import dayjs from 'dayjs'
import { Button, Field, PageTitle, Section, duration, number, tokens, useAdmin } from '../App'
import { download, get, post } from '../api'
import type { Account, RequestLog } from '../types'

const formatTime = (value?: string) => value ? dayjs(value).format('YYYY-MM-DD HH:mm:ss') : '-'
const keyLabel = (log: RequestLog, t: (value: string) => string) => log.apiKeyName ? `${log.apiKeyName} · ${log.apiKeyPreview || ''}` : log.apiKeyPreview === 'anonymous' ? t('匿名') : log.apiKeyPreview || '-'

export function Accounts() {
  const { t, run, notify } = useAdmin()
  const query = useQuery({ queryKey: ['accounts'], queryFn: async () => (await get<{ accounts: Account[] }>('accounts')).data.accounts || [] })
  const [page, setPage] = useState(1)
  const [selected, setSelected] = useState<string[]>([])
  const [expanded, setExpanded] = useState<string[]>([])
  const accounts = query.data || []
  const pages = Math.max(1, Math.ceil(accounts.length / 20))
  const visible = accounts.slice((Math.min(page, pages) - 1) * 20, Math.min(page, pages) * 20)
  const mutate = (path: string, body: unknown, success: string) => run(() => post(path, body), success)
  function toggle(id: string, checked: boolean) { setSelected(ids => checked ? [...ids, id] : ids.filter(x => x !== id)) }
  async function removeMany() { if (!selected.length || !confirm(`${t('确定删除选中的账号？')} (${selected.length})`)) return; await run(async () => { for (const accountId of selected) await post('accounts/delete', { accountId }); setSelected([]) }, '账号已删除') }
  async function exportData(ids?: string[]) { try { await download('accounts/export', ids); notify(t('账号已导出')) } catch (error) { notify((error as Error).message, true) } }
  return <><PageTitle title={t('账号管理')} subtitle={`${accounts.length} ${t('个账号')}`} action={<Button onClick={() => query.refetch()}>{t('刷新')}</Button>}/>
    <div className="mb-4 flex flex-wrap gap-2"><Button onClick={() => exportData()}>{t('导出全部')}</Button><Button onClick={() => exportData(selected)} disabled={!selected.length}>{t('导出选中')}</Button><Button onClick={() => run(() => post('accounts/refresh-all'), '刷新完成')}>{t('刷新全部 Token')}</Button><Button onClick={removeMany} disabled={!selected.length} danger>{t('删除选中')}</Button></div>
    <Section title={t('账号列表')}><div className="overflow-x-auto"><table className="account-table"><thead><tr><th><input type="checkbox" aria-label={t('全选本页')} checked={visible.length > 0 && visible.every(a => selected.includes(a.accountId))} onChange={e => setSelected(ids => e.target.checked ? [...new Set([...ids, ...visible.map(a => a.accountId)])] : ids.filter(id => !visible.some(a => a.accountId === id)))} /></th>{['邮箱', '状态', '请求', '输入', '输出', '总 Token', '缓存', '最后使用', '操作'].map(x => <th key={x}>{t(x)}</th>)}</tr></thead><tbody>{visible.map(a => <Fragment key={a.accountId}><tr className="account-summary-row"><td><input type="checkbox" checked={selected.includes(a.accountId)} onChange={e => toggle(a.accountId, e.target.checked)} aria-label={`${t('选择账号')} ${a.email}`}/></td><td>{a.email}</td><td>{t(a.status)}{a.cooldownUntil && <small> {formatTime(a.cooldownUntil)}</small>}</td><td>{number(a.usageCount)}</td><td>{tokens(a.promptTokens)}</td><td>{tokens(a.completionTokens)}</td><td>{tokens(a.totalTokens)}</td><td>{tokens(a.cachedTokens)}</td><td>{formatTime(a.lastUsed)}</td><td><div className="flex min-w-max justify-end gap-1"><button className="btn btn-sm" onClick={() => setExpanded(ids => ids.includes(a.accountId) ? ids.filter(x => x !== a.accountId) : [...ids, a.accountId])}>{t('模型')}</button><button className="btn btn-sm" onClick={() => mutate('accounts/test', { accountId: a.accountId }, '测试完成')}>{t('测试')}</button><button className="btn btn-sm" onClick={() => mutate('accounts/reset', { accountId: a.accountId }, '重置完成')}>{t('重置')}</button><button className="btn btn-sm btn-danger" onClick={() => confirm(t('确定删除此账号？')) && mutate('accounts/delete', { accountId: a.accountId }, '账号已删除')}>{t('删除')}</button></div></td></tr>{expanded.includes(a.accountId) && <tr><td colSpan={10}><div className="rounded-lg bg-neutral-50 p-3"><strong>{t('按模型统计（免费用量 + 首字延迟）')}</strong><div className="mt-2 grid gap-1 text-xs">{Object.values(a.modelStats || {}).map(st => <div key={st.modelId}>{st.modelId} · {number(st.usageCount)} req · {tokens(st.totalTokens)} tok {a.modelCooldowns?.[st.modelId] && `· ${t('冷却')} ${formatTime(a.modelCooldowns[st.modelId])}`} {a.modelLatencies?.[st.modelId] && `· TTFT ${duration(a.modelLatencies[st.modelId].ewmaMs)}`}</div>)}{!Object.keys(a.modelStats || {}).length && t('暂无数据')}</div></div></td></tr>}</Fragment>)}</tbody></table>{!accounts.length && <p className="p-6 text-center text-neutral-500">{query.error ? `${t('加载失败')}: ${query.error.message}` : t('暂无账号')}</p>}</div>{pages > 1 && <div className="account-pager"><span>{page} / {pages}</span><div className="flex gap-2"><button className="btn btn-sm" disabled={page <= 1} onClick={() => setPage(page - 1)}>{t('上一页')}</button><button className="btn btn-sm" disabled={page >= pages} onClick={() => setPage(page + 1)}>{t('下一页')}</button></div></div>}</Section>
  </>
}

function parseImport(text: string): unknown[] { try { const data: unknown = JSON.parse(text); if (Array.isArray(data)) return data; if (data && typeof data === 'object' && 'tokens' in data && Array.isArray(data.tokens)) return data.tokens; return [data] } catch { return text.split('\n').map(x => x.trim()).filter(Boolean).map(refreshToken => ({ refreshToken })) } }
export function ImportPage() {
  const { t, run, notify } = useAdmin()
  const [mode, setMode] = useState<'oauth'|'token'|'batch'>('oauth')
  const [session, setSession] = useState<{ sessionId: string; verificationUri: string; userCode: string } | null>(null)
  const [oauthResult, setOauthResult] = useState('')
  const [refreshToken, setRefreshToken] = useState('')
  const [email, setEmail] = useState('')
  const [batch, setBatch] = useState('')
  useEffect(() => { if (!session) return; const timer = setInterval(async () => { try { const result = (await get<{ done: boolean; success: boolean; email?: string; error?: string }>(`oauth/status?sessionId=${encodeURIComponent(session.sessionId)}`)).data; if (result.done) { clearInterval(timer); setSession(null); setOauthResult(result.success ? `${t('账号添加成功')}: ${result.email || ''}` : `${t('失败')}: ${result.error || ''}`) } } catch { /* retry polling */ } }, 2000); return () => clearInterval(timer) }, [session, t])
  async function importBatch(raw: string) { const tokens = parseImport(raw); if (!tokens.length) { notify(t('请输入账号数据'), true); return } await run(() => post('batch-import', { tokens }), '导入完成'); setBatch('') }
  async function fileChanged(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) await importBatch(await file.text()); event.target.value = '' }
  return <><PageTitle title={t('导入账号')} subtitle={t('OAuth、Refresh Token 或批量导入')}/><Section title={t('导入方式')}><div className="mb-5 flex gap-2" role="tablist">{(['oauth', 'token', 'batch'] as const).map(id => <button key={id} role="tab" aria-selected={mode === id} className={`tab ${mode === id ? 'active' : ''}`} onClick={() => setMode(id)}>{id === 'oauth' ? 'OAuth' : id === 'token' ? 'Token' : t('批量导入')}</button>)}</div>
    {mode === 'oauth' && <div role="tabpanel"><Button disabled={!!session} onClick={() => run(async () => { const result = (await post<{ sessionId: string; verificationUri: string; userCode: string }>('oauth/start')).data; setSession(result); setOauthResult('') })}>{t('开始 OAuth 登录')}</Button>{session && <div className="mt-4"><p>{t('请在浏览器中打开链接并输入代码')}</p><a href={session.verificationUri} onClick={e => { e.preventDefault(); run(() => get(`open-external?url=${encodeURIComponent(session.verificationUri)}`)) }} className="text-blue-600 underline">{session.verificationUri}</a><div className="mt-2 font-mono text-xl">{session.userCode}</div></div>}{oauthResult && <p className="mt-3">{oauthResult}</p>}</div>}
    {mode === 'token' && <form role="tabpanel" className="grid max-w-xl gap-4" onSubmit={(e: FormEvent) => { e.preventDefault(); run(() => post('accounts/add', { refreshToken, email: email || undefined }), '账号添加成功').then(() => { setRefreshToken(''); setEmail('') }) }}><Field label="Refresh Token"><textarea required rows={4} value={refreshToken} onChange={e => setRefreshToken(e.target.value)}/></Field><Field label={t('邮箱（可选）')}><input value={email} onChange={e => setEmail(e.target.value)}/></Field><Button type="submit">{t('添加账号')}</Button></form>}
    {mode === 'batch' && <div role="tabpanel" className="grid max-w-2xl gap-4"><Field label={t('账号数据')}><textarea rows={8} value={batch} onChange={e => setBatch(e.target.value)} placeholder="JSON / refreshToken per line"/></Field><div className="flex gap-3"><Button onClick={() => importBatch(batch)}>{t('批量导入')}</Button><label className="btn cursor-pointer">{t('选择文件')}<input type="file" accept=".json,.txt" className="sr-only" onChange={fileChanged}/></label></div></div>}
  </Section></>
}

type LogPage = { items: RequestLog[]; nextCursor?: string; hasMore: boolean }
export function Logs() {
  const { t } = useAdmin()
  const [cursor, setCursor] = useState('')
  const [entries, setEntries] = useState<RequestLog[]>([])
  const [selected, setSelected] = useState<RequestLog | null>(null)
  const dialog = useRef<HTMLDialogElement>(null)
  const query = useQuery({ queryKey: ['request-logs', cursor], queryFn: async () => (await get<LogPage>(`request-logs?limit=50${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ''}`)).data })
  useEffect(() => { if (!query.data) return; setEntries(previous => cursor ? [...previous, ...query.data!.items] : query.data!.items) }, [query.data, cursor])
  function open(log: RequestLog) { setSelected(log); dialog.current?.showModal() }
  function refresh() { setEntries([]); setCursor(''); query.refetch() }
  return <><PageTitle title={t('请求日志')} subtitle={t('查看调用和错误详情')} action={<Button onClick={refresh}>{t('刷新')}</Button>}/><Section title={t('最近请求')}><div className="overflow-x-auto"><table className="log-table"><thead><tr>{['时间', '账号 / 渠道', '调用 API Key', '协议', '模型', '输入', '输出', '缓存', '总 Token', '耗时', '首字延迟', 'tok/s', '状态'].map(x => <th key={x}>{t(x)}</th>)}</tr></thead><tbody>{entries.map(l => <tr key={l.id}><td className="whitespace-nowrap">{formatTime(l.startedAt)}</td><td>{l.accountEmail || l.upstream || '-'}</td><td className="font-mono text-xs">{keyLabel(l, t)}</td><td>{l.protocol}</td><td className="font-mono text-xs">{l.model}</td><td>{l.usageAvailable ? tokens(l.inputTokens) : '-'}</td><td>{l.usageAvailable ? tokens(l.outputTokens) : '-'}</td><td>{l.usageAvailable ? tokens(l.cachedTokens) : '-'}</td><td>{l.usageAvailable ? tokens(l.totalTokens) : '-'}</td><td>{duration(l.durationMs)}</td><td>{duration(l.ttftMs)}</td><td>{l.outputTokensPerSecond?.toFixed(1) || '-'}</td><td><span className={`log-status ${l.completed ? 'ok' : 'fail'}`}>{t(l.completed ? '完成' : '失败')}</span>{!l.completed && <button className="log-detail-trigger" onClick={() => open(l)}>{t('详情')}</button>}</td></tr>)}</tbody></table>{!entries.length && <div className="empty">{query.isLoading ? t('加载中…') : query.error ? `${t('加载失败')}: ${query.error.message}` : t('暂无请求日志')}</div>}</div>{query.data?.hasMore && <button className="btn mt-4" onClick={() => setCursor(query.data?.nextCursor || '')}>{t('加载更多')}</button>}</Section>
    <dialog ref={dialog} className="m-auto w-[min(90vw,720px)] rounded-2xl border border-neutral-200 p-6 shadow-2xl backdrop:bg-black/50" onClose={() => setSelected(null)}><div className="mb-5 flex justify-between"><h2 className="text-lg font-semibold">{t('请求详情')}</h2><button aria-label={t('关闭')} onClick={() => dialog.current?.close()}>✕</button></div>{selected && <><dl className="grid grid-cols-2 gap-3 text-sm">{([['请求 ID', selected.id], ['时间', formatTime(selected.startedAt)], ['账号 / 渠道', selected.accountEmail || selected.upstream || '-'], ['调用 API Key', keyLabel(selected, t)], ['API Key ID', selected.apiKeyId || '-'], ['协议', selected.protocol], ['模型', selected.model], ['错误代码', selected.errorCode || '-']] as const).map(([label, value]) => <div key={label}><dt className="text-neutral-500">{t(label)}</dt><dd className="break-all font-mono">{value}</dd></div>)}</dl><h3 className="mt-5 font-semibold">{t('错误详情')}</h3><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap rounded-lg bg-neutral-100 p-3 text-sm">{[selected.error, selected.errorCode && `code=${selected.errorCode}`, selected.finishReason && `finish=${selected.finishReason}`, selected.retryCount && `retries=${selected.retryCount}`, selected.upstreamAttempts && `upstream_attempts=${selected.upstreamAttempts}`, selected.retrySuppressed && 'retry_suppressed=true'].filter(Boolean).join('\n') || t('未记录错误信息')}</pre></>}</dialog>
  </>
}
