/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ModelVisibilityRouteImport } from './routes/model-visibility'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAdvancedRouteImport } from './routes/settings.advanced'
import { Route as SettingsApiKeysRouteImport } from './routes/settings.api-keys'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsModelsRouteImport } from './routes/settings.models'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsUpstreamsRouteImport } from './routes/settings.upstreams'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelVisibilityRoute = ModelVisibilityRouteImport.update({
  id: '/model-visibility',
  path: '/model-visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUpstreamsRoute = SettingsUpstreamsRouteImport.update({
  id: '/upstreams',
  path: '/upstreams',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/import': typeof ImportRoute
  '/logs': typeof LogsRoute
  '/model-visibility': typeof ModelVisibilityRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/upstreams': typeof SettingsUpstreamsRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/import': typeof ImportRoute
  '/logs': typeof LogsRoute
  '/model-visibility': typeof ModelVisibilityRoute
  '/providers': typeof ProvidersRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/upstreams': typeof SettingsUpstreamsRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/import': typeof ImportRoute
  '/logs': typeof LogsRoute
  '/model-visibility': typeof ModelVisibilityRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/upstreams': typeof SettingsUpstreamsRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accounts'
    | '/import'
    | '/logs'
    | '/model-visibility'
    | '/providers'
    | '/settings'
    | '/settings/advanced'
    | '/settings/api-keys'
    | '/settings/general'
    | '/settings/models'
    | '/settings/security'
    | '/settings/upstreams'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accounts'
    | '/import'
    | '/logs'
    | '/model-visibility'
    | '/providers'
    | '/settings/advanced'
    | '/settings/api-keys'
    | '/settings/general'
    | '/settings/models'
    | '/settings/security'
    | '/settings/upstreams'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accounts'
    | '/import'
    | '/logs'
    | '/model-visibility'
    | '/providers'
    | '/settings'
    | '/settings/advanced'
    | '/settings/api-keys'
    | '/settings/general'
    | '/settings/models'
    | '/settings/security'
    | '/settings/upstreams'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountsRoute: typeof AccountsRoute
  ImportRoute: typeof ImportRoute
  LogsRoute: typeof LogsRoute
  ModelVisibilityRoute: typeof ModelVisibilityRoute
  ProvidersRoute: typeof ProvidersRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-visibility': {
      id: '/model-visibility'
      path: '/model-visibility'
      fullPath: '/model-visibility'
      preLoaderRoute: typeof ModelVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/upstreams': {
      id: '/settings/upstreams'
      path: '/upstreams'
      fullPath: '/settings/upstreams'
      preLoaderRoute: typeof SettingsUpstreamsRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsUpstreamsRoute: typeof SettingsUpstreamsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsUpstreamsRoute: SettingsUpstreamsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountsRoute: AccountsRoute,
  ImportRoute: ImportRoute,
  LogsRoute: LogsRoute,
  ModelVisibilityRoute: ModelVisibilityRoute,
  ProvidersRoute: ProvidersRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
